models/acl/openconfig-acl.yang
#models/bgp/openconfig-bgp-policy.yang
models/ptp/openconfig-ptp.yang
#models/ospf/openconfig-ospf-policy.yang
models/lldp/openconfig-lldp.yang
#models/isis/openconfig-isis-policy.yang
models/qos/openconfig-qos.yang
#models/stp/openconfig-spanning-tree.yang
models/vlan/openconfig-vlan.yang
models/telemetry/openconfig-telemetry.yang
#models/system/openconfig-system.yang
#models/lacp/openconfig-lacp.yang
#models/oam/openconfig-oam.yang
models/nat/openconfig-nat.yang
#models/interfaces/openconfig-interfaces.yang
#models/network-instance/openconfig-network-instance.yang
#models/keychain/openconfig-keychain.yang
#models/segment-routing/openconfig-rsvp-sr-ext.yang
#models/macsec/openconfig-macsec.yang
#models/openflow/openconfig-openflow.yang
#models/security/openconfig-security.yang
#models/flex-algo/openconfig-flexalgo.yang
#models/ethernet-segments/openconfig-ethernet-segments.yang
#models/ate/openconfig-ate-flow.yang
#models/firewall/openconfig-fw-high-availability.yang
#models/policy/openconfig-routing-policy.yang
#models/policy-forwarding/openconfig-pf-srte.yang
#models/relay-agent/openconfig-relay-agent.yang
#models/probes/openconfig-probes.yang