# Start from the base image that already contains supervisord and basic SONiC tools
{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

#
# (Assumes that libconfig, etc., were installed as dependencies by the .deb)
#
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        iproute2 \
        libconfig9 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#
# The 'docker_test_debs' variable is passed in from the docker-test.mk file
# It will contain the 'linuxtest_....deb' file
#
{% if docker_test_debs.strip() -%}
# Copy our .deb package into the container
{{ copy_files("debs/", docker_test_debs.split(' '), "/debs/") }}

# Install the .deb package (and its dependencies)
{{ install_debian_packages(docker_test_debs.split(' ')) }}
{%- endif %}

#
# Install Python wheel packages (if any)
# Our .mk file added SONIC_PY_COMMON_PY3
#

{% if docker_test_whls.strip() -%}
# Copy the .wheel files into the container
{{ copy_files("python-wheels/", docker_test_whls.split(' '), "/python-wheels/") }}

# Install the .python-wheels
{{ install_python_wheels(docker_test_whls.split(' ')) }}
{%- endif %}

#
# Final cleanup
#
RUN apt-get clean -y      && \
    apt-get autoclean -   && \
    apt-get autoremove -y && \
    rm -rf /debs /python-wheels /var/lib/apt/lists/* /tmp/* ~/.cache/

#
# Copy the test-SPECIFIC supervisord config file.
#
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

# (Optional) Copy any helper scripts you need
# COPY ["start.sh", "/usr/bin/start.sh"]
COPY ["test_clid.py", "/usr/local/bin/test_clid.py"]


# Entrypoint is inherited from the base image
# (which is already /usr/local/bin/supervisord)
ENTRYPOINT ["/usr/local/bin/supervisord"]

