---

connection:
  host: "192.168.122.5"
  port: "22"
  user: "admin"
  password: "YourPaSsWoRd"
  timeout: 3

nodes:
  - VIEW_NODE
  - CONFIG_NODE
  #- BGP_NODE
  #- VRF_NODE
  #- SEGMENT_ROUTING_NODE
  #- RPKI_NODE
  #- RIPNG_NODE
  #- RIP_NODE
  #- OSPF6_NODE
  #- OSPF_NODE
  #- OPENFABRIC_NODE
  #- ISIS_NODE
  #- EIGRP_NODE
  #- BABEL_NODE
  - RMAP_NODE
  #- PW_NODE
  #- PBRMAP_NODE
  #- NH_GROUP_NODE
  #- LDP_NODE
  #- VTY_NODE
  #- LDP_L2VPN_NODE
  #- KEYCHAIN_NODE
  #- INTERFACE_NODE
  #- BFD_NODE

regexps:
  A.B.C.D/M: "1.1.1.1/32"
  A.B.C.D: "1.1.1.2"
  X:X::X:X/M: "2001:db8::1/128"
  X:X::X:X: "2001:db8::1"
  INTERFACE: "eth99"
  IFNAME: "eth88"
  AA:BB:CC...: "11:11:11 22:22:22"
  AA:BB:CC: "11:11:11"
  AA:AA:NN: "22:22:22"
  AA:AA:NN...: "22:22:22 3:3:3"
  AA:NN...: "11:11 22:22"
  AA:NN: "11:11"
  ASN:nn_or_IP-address:nn: "11:11"
  ASN:NN_OR_IP-ADDRESS:NN: "11:11"
  RTLIST...: "rtlist rtlistxxx"
  YY:YY:YY:YY:YY:YY: "11:11:11:11:11:11"
  MAC: "11:11:11:11:11:12"
  X:X:X:X:X:X: "11:11:11:11:11:13"
  M:A:C: "11:11:11:11:11:14"
  M:A:C/M: "11:11:11:11:11:11/48"
  HH:MM:SS: "10:10:10"
  MONTH: "January"
  BANDWIDTH: "1000"
  PERCENTAGE: "50"
  REGEX...: "router1 router2"
  LINE...: "line1 line2"
  MSG...: "msg1 msg2"
  PROFILE...: "profile1 profile2"
  VERSION...: "version1 version2"
  LNH_OPTIONS...: "option1 option2"
  LCOMMUNITY_LIST_NAME: "listcommunity1"
  COMMUNITY_LIST_NAME: "listcommunity2"
  EXTCOMMUNITY_LIST_NAME: "listcommunity3"
  FRR_REDIST_STR_OSPFD: "connected"
  CMD_RANGE_STR: "123"
  VIEWVRFNAME: "all"
  ACCESSLIST_NAME: "accesslistname"
  RMAP_NAME: "rmapname"
  PROTO_IP6_REDIST_STR: "protoipv6"
  ISIS_MT_NAMES: "isismtname"
  AUTH_KEY: "authenkey"
  KEYCHAIN_NAME: "keychain"
  (1-4294967295)...: '123'
  ASN:NN_OR_IP-ADDRESS:NN...: '11:22 22:33'
  OPTVAL: 'inputoptval'